name: tic_tac_toe_game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tic_tac_toe_lib:
    path: dependencies/tic_tac_toe_lib
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  flutter_gen: ^5.3.1
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  confetti: ^0.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
