name: tic_tac_toe_game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tic_tac_toe_lib:
    path: dependencies/tic_tac_toe_lib
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  flutter_gen: ^5.3.1
  google_fonts: ^5.1.0
  audioplayers: ^5.1.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launch_icon"
  ios: true
  image_path: "assets/images/launch_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/launch_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/launch_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/launch_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
